apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aad-63bd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aad-63bd"
  template:
    metadata:
      labels:
        app: "aad-63bd"
    spec:
      containers:
        - name: "aad-63bd"
          image: "test234343.azurecr.io/aad"
          ports:
          - containerPort: 80