apiVersion: v1
kind: Service
metadata:
    name: "aad-63bd"
    labels:
        app: "aad-63bd"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aad-63bd"